package discover

import (
	"fmt"
	"strings"
)

// YAML turns a Snapshot into a starter revenant.yaml.
//
// It encodes what we can guess from the catalog. Domain rules (refunds never
// exceed orders, etc.) still have to be added by the user as extra golden_query
// checks — Revenant cannot invent those.
func YAML(plan string, snap *Snapshot) (string, error) {
	if plan == "" {
		return "", fmt.Errorf("plan name is required")
	}
	if len(snap.Tables) == 0 {
		return "", fmt.Errorf("no tables found in schema %q", snap.Schema)
	}

	var b strings.Builder
	b.WriteString("# Generated by: revenant init\n")
	b.WriteString("# Review this file, then run: revenant verify\n")
	b.WriteString("#\n")
	b.WriteString("# Revenant does not read your app source. These checks talk to a live database.\n")
	b.WriteString("# Add your own golden_query checks for business rules we cannot guess.\n\n")

	fmt.Fprintf(&b, "plan: %s\n\n", plan)
	b.WriteString("database:\n")
	b.WriteString("  engine: postgres\n")
	b.WriteString("  connection: ${DATABASE_URL}\n\n")
	b.WriteString("checks:\n")

	b.WriteString("  - type: schema\n")
	b.WriteString("    expect_tables:\n")
	for _, t := range snap.Tables {
		fmt.Fprintf(&b, "      - %s\n", t)
	}
	b.WriteString("\n")

	for _, t := range snap.Tables {
		n := snap.Counts[t]
		if n < 1 {
			continue
		}
		b.WriteString("  - type: row_count\n")
		fmt.Fprintf(&b, "    table: %s\n", t)
		fmt.Fprintf(&b, "    min: %d\n\n", n)
	}

	for _, fk := range snap.FKs {
		b.WriteString("  - type: foreign_key\n")
		fmt.Fprintf(&b, "    table: %s\n", fk.Table)
		fmt.Fprintf(&b, "    references: %s\n\n", fk.References)
	}

	if golden, ok := pickGolden(snap); ok {
		b.WriteString("  - type: golden_query\n")
		fmt.Fprintf(&b, "    query: \"SELECT count(*) FROM %s\"\n", golden)
		b.WriteString("    expect_min: 1\n")
	}

	return b.String(), nil
}

func pickGolden(snap *Snapshot) (string, bool) {
	best := ""
	bestN := 0
	for _, t := range snap.Tables {
		if snap.Counts[t] > bestN {
			bestN = snap.Counts[t]
			best = t
		}
	}
	if bestN < 1 {
		return "", false
	}
	return best, true
}
